baseURL: https://pollydrive.github.io
languageCode: ru-ru
title: σχολή
theme: "PaperMod"

params:
  homeInfoParams:
    Title: Школа
    Content: Книжки читаю, пишу по ним конспекты

  socialIcons: # optional
    # - name: "youtube"
    #   url: "https://www.youtube.com/channel/UCfdvqLvTzcyw6iRnHq-JQZA"
    # - name: "telegram"
    #   url: "https://t.me/polly_station"
    # - name: "kofi"
    #   url: "https://buymeacoffee.com/XXX"
    # - name: "rss"
    #   url: "https://XXX.github.io/index.xml"
  ShowReadingTime: false
  # author: "Polly"
  # contact: "@PollyDrive"
  # feedlinks: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  mobileMenu: true
  comments: false
 #Google Analytics 4 optional
  env: #production
  GoogleAnalytics: "G-00000XXXXX" 
  sitemap:
    changefreq: daily
    filename: sitemap.xml
    priority: 0.5
services:
  disqus:
    shortname: alinekravetz
taxonomies:
  category: categories
  authors: authors
  works: works
  series: series 
  lecturer: lecturer
  tag: tags
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: categories
      name: Категории
      url: /categories/
      weight: 10
    - identifier: authors
      name: Авторы
      url: /authors/
      weight: 20
    - identifier: works
      name: Работы
      url: /works/
      weight: 20
    # - name: Series
    #   pageRef: /works/series/
    #   parent: Works
    #   weight: 10
    - identifier: tags
      name: Теги
      url: /tags/
      weight: 20
    - identifier: search
      name: Поиск
      url: /search/
      weight: 30

    # - identifier: archive
    #   name: Архив
    #   url: /archives/
    #   weight: 20

